version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public  # Prisma DB URL
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./backend:/app  # Mount the backend source for live reloading (optional)

  db:
    image: postgres:13
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
    driver: local
