version: '3.8'

services:
  frontend:
    build:
      context: .  # Path to the frontend directory
    container_name: frontend-container
    ports:
      - "8080:80"  # Expose frontend app on port 8080 (map to container's port 80)
    networks:
      - frontend-network
    environment:
      NODE_ENV: production
    restart: always

networks:
  frontend-network:
    driver: bridge
