services:
  db:
    image: postgres:13
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "5000:5000"
    depends_on:
      - db
    entrypoint: /wait-for-it.sh db:5432 -- npm run start
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/db?schema=public
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgres-data:
    driver: local

networks:
  backend:
    driver: bridge
